- name: This playbook will install notepad++ on azure windows 2019 server
  hosts: all
  tasks:
  - name: Install notepad plus plus
    win_chocolatey:
      name: notepadplusplus
      state: latest

  - name: Install Adobe Acrobat Reader
    win_chocolatey:
      name: adobereader
      state: latest

  - name: Download Python 
    win_get_url:
      url: https://www.python.org/ftp/python/3.10.6/python-3.10.6.exe 
      dest: C:\python-3.10.6.exe
    tags:
    - python 

  - name: Install python 
    win_package:
      path: C:\python-3.10.6.exe
      state: present
      arguments: 
      - '/quiet'
      - '/layout C:\Python123'
        
    tags:
    - python 
