#!/usr/bin/env groovy
pipeline {
    agent {
        label 'docker-jenkins-slave'
    }
    stages {
        stage('Compile') {
            steps {
                script {
                    dir("Day9/simple-java-app") {
                        sh "mvn clean compile"
                    }
                }
            }
        }
        stage('Unit Test') {
            steps {
                script {
                    dir("Day9/simple-java-app") {
                        sh "mvn test"
                    }
                }
            }
        }
        stage('package') {
            steps {
                script {
                    dir("Day9/simple-java-app") {
                        sh "mvn package"
                    }
                }
            }
        }
        stage('Install') {
            steps {
                script {
                    dir("Day9/simple-java-app") {
                        sh "mvn install"
                    }
                }
            }
        }
    }
}
