- name: This playbook will install nginx, configures web root folder, deploys custom web page
  hosts: all
  vars_files:
  - nginx_vars.yml

  tasks:
  - include_tasks: "install-nginx-{{ansible_distribution|lower}}.yml"
  - include_tasks: "configure-nginx-{{ansible_distribution|lower}}.yml"
  - include_tasks: "restart-nginx-{{ansible_distribution|lower}}.yml"

  - include_tasks: deploy-custom-webpage.yml
