- name: Install Extra packages for Enterprise Linux (EPEL) in CentOS 
  when: ansible_distribution == "CentOS" and ansible_os_family == "RedHat"
  yum: name=epel-release state=latest 

- name: Install nginx in CentOS 
  when: ansible_distribution == "CentOS" and ansible_os_family == "RedHat"
  yum: name=nginx state=latest 
