- name: Builds a custom docker image
  hosts: localhost
  vars:
  - docker_image_names:
    - tektutor/ansible-ubuntu:latest
    - tektutor/ansible-centos:latest
    
  tasks:

  - name: Delete any containers if exists
    shell: docker rm -f $(docker ps -aq)
    ignore_errors: true

  - name: Remove existing image
    shell: docker rmi "{{item}}" 
    ignore_errors: true
    with_lists: "{{docker_image_names}}"

  - name: Copy the public key to current directory
    shell: cp ~/.ssh/id_rsa.pub authorized_keys

  - name: Build ubuntu ansible node docker image
    docker_image:
      name: tektutor/ansible-ubuntu:latest
      state: present
      source: build
      build:
        dockerfile: UbuntuDockerfile
        path: .
        pull: no

  - name: Build centos ansible node docker image
    docker_image:
      name: tektutor/ansible-centos:latest
      state: present
      source: build
      build:
        dockerfile: CentOSDockerfile
        path: .
        pull: no


  - name: Delete the authorized_keys
    shell: rm ./authorized_keys
