- name: This playbook demonstrates invoke ping module
  hosts: all
  gather_facts: no
  tasks:
  - name: Fist task - Ping
    ping:

  - debug: msg="end of first task"

  - name: Second task - Ping
    ping:
