- name: Install Extra packages for Enterprise Linux (EPEL) in CentOS 
  when: ansible_distribution == "CentOS"
  yum: name=epel-release state=latest 

- name: Install nginx in CentOS 
  when: ansible_distribution == "CentOS"
  yum: name=nginx state=latest 
