- name: Invokes custom ansible module
  hosts: all 
  tasks:
  - name: Invoke hello custom module
    hello: message="Hello Custom Ansible Module !"
    register: output

  - debug: var=output
  
  - name: Invoke add custom module
    add: 
      input1: 10.5 
      input2: 21.3
    register: result

  - debug: var=result

  - name: Retrieve IP ansible node IP address
    get_ip:
    register: result
    tags:
    - ip

  - debug: var=result
    tags:
    - ip
